## 1.Financial Variables

In [2]:
# import the data downloaded from CompuStat
import pandas as pd
import numpy as np

df = pd.read_excel("reprawdata.xlsx")

In [3]:
df.head(10)

,costat,curcdq,datafmt,indfmt,consol,gvkey,datadate,cusip,addzip,city,...,sic,atq,ceqq,cshoq,dlcq,dlttq,ibq,ppentq,capxy,prccq
0,I,USD,STD,INDL,C,1013,2001-01-31,886309,55344-2252,Eden Prairie,...,3661,3722.000,2576.800,780.800,186.500,15.000,-7.600,682.600,93.300,14.5625
1,I,USD,STD,INDL,C,1082,2001-01-31,81765M106,30339-2029,Atlanta,...,8700,97.432,22.461,2.950,1.361,51.098,-0.861,28.360,0.365,4.1250
2,I,USD,STD,INDL,C,1173,2001-01-31,8015307,33765,Clearwater,...,3812,21.473,13.131,3.920,1.019,4.335,0.438,4.157,0.238,12.1000
3,I,USD,STD,INDL,C,1183,2001-01-31,45169P106,10017,New York,...,4899,39.066,31.455,11.519,0.000,0.000,-42.414,0.789,0.188,0.2850
4,I,USD,STD,INDL,C,1240,2001-01-31,13104104,83706,Boise,...,5411,16078.000,5694.000,405.000,82.000,5942.000,220.000,9622.000,1771.000,28.3500
5,I,USD,STD,INDL,C,1259,2001-01-31,87509Q105,7078,Short Hills,...,2836,0.357,-0.257,18.887,0.007,0.027,-0.688,0.104,0.000,0.9060
6,I,USD,STD,INDL,C,1363,2001-01-31,86584307,75251,Dallas,...,7359,26.809,8.792,1.695,NaN,15.489,-0.196,22.570,7.663,3.8750
7,A,USD,STD,INDL,C,1410,2001-01-31,957100,10006,New York,...,7340,638.237,327.651,23.379,3.736,35.811,8.404,40.527,3.478,30.3500
8,I,USD,STD,INDL,C,1441,2001-01-31,56418U101,NaN,Central,...,3350,41.703,31.894,15.094,0.000,0.000,-2.332,1.069,0.278,4.0500
9,I,USD,STD,INDL,C,1444,2001-01-31,03037B106,89180,Las Vegas,...,7822,18.320,17.887,4.866,0.000,0.000,-0.250,5.030,0.000,1.5000

In [4]:
# delete samples in finance industry
df = df[
    (df['sic'] < 6000)
    | (df['sic'] > 6999)
]

In [5]:
# manage dates
df['datadate'] = pd.to_datetime(df['datadate'])
df = df.sort_values(['gvkey', 'datadate'])
df.head(10)

,costat,curcdq,datafmt,indfmt,consol,gvkey,datadate,cusip,addzip,city,...,sic,atq,ceqq,cshoq,dlcq,dlttq,ibq,ppentq,capxy,prccq
900,A,USD,STD,INDL,C,1004,2001-02-28,361105,60191,Wood Dale,...,5080,754.718,344.865,26.945,49.665,180.106,5.388,108.040,9.371,13.60
11819,A,USD,STD,INDL,C,1004,2001-05-31,361105,60191,Wood Dale,...,5080,701.854,340.212,26.937,13.652,179.987,5.706,108.907,13.134,14.00
22539,A,USD,STD,INDL,C,1004,2001-08-31,361105,60191,Wood Dale,...,5080,758.503,340.147,26.958,65.396,189.920,0.486,108.074,3.000,17.06
33057,A,USD,STD,INDL,C,1004,2001-11-30,361105,60191,Wood Dale,...,5080,714.208,284.344,26.876,71.162,189.733,-54.484,105.513,6.141,8.15
43277,A,USD,STD,INDL,C,1004,2002-02-28,361105,60191,Wood Dale,...,5080,690.681,314.832,31.859,20.890,189.665,-2.290,103.760,8.448,7.40
53743,A,USD,STD,INDL,C,1004,2002-05-31,361105,60191,Wood Dale,...,5080,710.199,310.235,31.870,42.525,217.699,-2.651,102.591,12.112,11.44
64014,A,USD,STD,INDL,C,1004,2002-08-31,361105,60191,Wood Dale,...,5080,722.944,306.560,31.865,41.989,246.822,-4.879,101.259,2.266,6.20
74121,A,USD,STD,INDL,C,1004,2002-11-30,361105,60191,Wood Dale,...,5080,727.776,306.234,31.843,91.772,195.268,-0.663,96.000,4.883,5.50
83974,A,USD,STD,INDL,C,1004,2003-02-28,361105,60191,Wood Dale,...,5080,723.019,309.093,31.851,121.789,161.362,0.651,95.548,7.917,4.45
94089,A,USD,STD,INDL,C,1004,2003-05-31,361105,60191,Wood Dale,...,5080,686.621,294.988,31.851,92.256,164.658,-7.519,166.761,9.930,4.50

In [6]:
# Tobin's q
df['mve'] = df['prccq'] * df['cshoq']

df['tobinq'] = (
    df['mve']
    + df['atq']
    - df['ceqq']
) / df['atq']

In [7]:
# Controls
df['log_assets'] = np.log(df['atq'])

df['capex'] = df['capxy'] / df['atq']

df['ppe'] = df['ppentq'] / df['atq']

df['book_leverage'] = (
    df['dlttq'] + df['dlcq']
) / df['atq']

df['roa'] = df['ibq'] / df['atq']

C:\Users\明裕佳\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\明裕佳\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

In [8]:
# take lags
controls = [
    'log_assets',
    'capex',
    'ppe',
    'book_leverage',
    'roa'
]

for v in controls:
    df[v+'_lag'] = df.groupby('gvkey')[v].shift(1)

In [9]:
# industry*quarter fe
df['quarter'] = df['datadate'].dt.to_period('Q')
df['naics2'] = (
    df['naics']
      .astype(str)
      .str[:2]
)

df['ind_quar_fe'] = (
    df['naics2'].astype(str)
    + "_"
    + df['quarter'].astype(str)
)
df.head(10)

,costat,curcdq,datafmt,indfmt,consol,gvkey,datadate,cusip,addzip,city,...,book_leverage,roa,log_assets_lag,capex_lag,ppe_lag,book_leverage_lag,roa_lag,quarter,naics2,ind_quar_fe
900,A,USD,STD,INDL,C,1004,2001-02-28,361105,60191,Wood Dale,...,0.304446,0.007139,NaN,NaN,NaN,NaN,NaN,2001Q1,42,42_2001Q1
11819,A,USD,STD,INDL,C,1004,2001-05-31,361105,60191,Wood Dale,...,0.275896,0.008130,6.626344,0.012417,0.143153,0.304446,0.007139,2001Q2,42,42_2001Q2
22539,A,USD,STD,INDL,C,1004,2001-08-31,361105,60191,Wood Dale,...,0.336605,0.000641,6.553725,0.018713,0.155170,0.275896,0.008130,2001Q3,42,42_2001Q3
33057,A,USD,STD,INDL,C,1004,2001-11-30,361105,60191,Wood Dale,...,0.365293,-0.076286,6.631347,0.003955,0.142483,0.336605,0.000641,2001Q4,42,42_2001Q4
43277,A,USD,STD,INDL,C,1004,2002-02-28,361105,60191,Wood Dale,...,0.304851,-0.003316,6.571174,0.008598,0.147734,0.365293,-0.076286,2002Q1,42,42_2002Q1
53743,A,USD,STD,INDL,C,1004,2002-05-31,361105,60191,Wood Dale,...,0.366410,-0.003733,6.537678,0.012231,0.150229,0.304851,-0.003316,2002Q2,42,42_2002Q2
64014,A,USD,STD,INDL,C,1004,2002-08-31,361105,60191,Wood Dale,...,0.399493,-0.006749,6.565545,0.017054,0.144454,0.366410,-0.003733,2002Q3,42,42_2002Q3
74121,A,USD,STD,INDL,C,1004,2002-11-30,361105,60191,Wood Dale,...,0.394407,-0.000911,6.583332,0.003134,0.140065,0.399493,-0.006749,2002Q4,42,42_2002Q4
83974,A,USD,STD,INDL,C,1004,2003-02-28,361105,60191,Wood Dale,...,0.391623,0.000900,6.589993,0.006709,0.131909,0.394407,-0.000911,2003Q1,42,42_2003Q1
94089,A,USD,STD,INDL,C,1004,2003-05-31,361105,60191,Wood Dale,...,0.374171,-0.010951,6.583436,0.010950,0.132151,0.391623,0.000900,2003Q2,42,42_2003Q2

In [11]:
# output: finvar.xlsx
keep_cols = [
    'gvkey',
    'datadate',
    'cusip',
    'naics',
    'sic',

    'tobinq',
    
    'log_assets_lag',
    'capex_lag',
    'ppe_lag',
    'book_leverage_lag',
    'roa_lag',

    'ind_quar_fe'
]
df_fin = df[keep_cols]
df_fin.to_excel(
    "finvar.xlsx",
    index=False
)