## 2.Firm-level Climate Scores

### 2.1 Sautner et al. (2023)

In [2]:
import pandas as pd
import numpy as np

sautner = pd.read_excel("firmquarter_score_2024Q4_Version_2025_Jul_03.xlsx")
sautner = sautner[sautner["hqcountrycode"] == "US"].copy()
sautner.head(10)

,isin,year,quarter,cc_expo_ew,cc_risk_ew,cc_pos_ew,cc_neg_ew,cc_sent_ew,op_expo_ew,op_risk_ew,...,rg_neg_ew,rg_sent_ew,ph_expo_ew,ph_risk_ew,ph_pos_ew,ph_neg_ew,ph_sent_ew,gvkey,cusip,hqcountrycode
364,AN8068571086,2003,3,0.000964,0.0,0.000321,-0.000643,-0.000321,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9465.0,806857108,US
365,AN8068571086,2004,1,0.000376,0.0,0.000000,-0.000376,-0.000376,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9465.0,806857108,US
366,AN8068571086,2004,2,0.000403,0.0,0.000000,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9465.0,806857108,US
367,AN8068571086,2004,3,0.000420,0.0,0.000000,-0.000840,-0.000840,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9465.0,806857108,US
368,AN8068571086,2004,4,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9465.0,806857108,US
369,AN8068571086,2005,1,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9465.0,806857108,US
370,AN8068571086,2005,2,0.000366,0.0,0.000000,-0.000366,-0.000366,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9465.0,806857108,US
371,AN8068571086,2005,3,0.000679,0.0,0.000340,0.000000,0.000340,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9465.0,806857108,US
372,AN8068571086,2005,4,0.000361,0.0,0.000361,0.000000,0.000361,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9465.0,806857108,US
373,AN8068571086,2006,1,0.000354,0.0,0.000000,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9465.0,806857108,US

In [5]:
# repair 'gvkey'
sautner["gvkey"] = (
    pd.to_numeric(sautner["gvkey"], errors="coerce")
      .astype("Int64")
)

In [4]:
# link finvar.xlsx
fin = pd.read_excel("finvar.xlsx")
fin.head(10)

,gvkey,datadate,cusip,naics,sic,tobinq,log_assets_lag,capex_lag,ppe_lag,book_leverage_lag,roa_lag,ind_quar_fe
0,1004,2001-02-28,361105,423860.0,5080,1.028603,NaN,NaN,NaN,NaN,NaN,42_2001Q1
1,1004,2001-05-31,361105,423860.0,5080,1.052584,6.626344,0.012417,0.143153,0.304446,0.007139,42_2001Q2
2,1004,2001-08-31,361105,423860.0,5080,1.157885,6.553725,0.018713,0.155170,0.275896,0.008130,42_2001Q3
3,1004,2001-11-30,361105,423860.0,5080,0.908564,6.631347,0.003955,0.142483,0.336605,0.000641,42_2001Q4
4,1004,2002-02-28,361105,423860.0,5080,0.885511,6.571174,0.008598,0.147734,0.365293,-0.076286,42_2002Q1
5,1004,2002-05-31,361105,423860.0,5080,1.076539,6.537678,0.012231,0.150229,0.304851,-0.003316,42_2002Q2
6,1004,2002-08-31,361105,423860.0,5080,0.849232,6.565545,0.017054,0.144454,0.366410,-0.003733,42_2002Q3
7,1004,2002-11-30,361105,423860.0,5080,0.819866,6.583332,0.003134,0.140065,0.399493,-0.006749,42_2002Q4
8,1004,2003-02-28,361105,423860.0,5080,0.768532,6.589993,0.006709,0.131909,0.394407,-0.000911,42_2003Q1
9,1004,2003-05-31,361105,423860.0,5080,0.779123,6.583436,0.010950,0.132151,0.391623,0.000900,42_2003Q2

In [6]:
# link finvar.xlsx
fin = pd.read_excel("finvar.xlsx")
fin["datadate"] = pd.to_datetime(fin["datadate"])
fin["year"] = fin["datadate"].dt.year
fin["quarter"] = fin["datadate"].dt.quarter

sautnerfin = fin.merge(
    sautner,
    on=['gvkey', 'year', 'quarter'],
    how='inner'
)

In [7]:
print(len(fin))
print(len(sautner))
print(len(sautnerfin))

615927
259954
204208

In [8]:
sautnerfin.head(10)

,gvkey,datadate,cusip_x,naics,sic,tobinq,log_assets_lag,capex_lag,ppe_lag,book_leverage_lag,...,rg_pos_ew,rg_neg_ew,rg_sent_ew,ph_expo_ew,ph_risk_ew,ph_pos_ew,ph_neg_ew,ph_sent_ew,cusip_y,hqcountrycode
0,1004,2002-02-28,361105,423860.0,5080,0.885511,6.571174,0.008598,0.147734,0.365293,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,000361105,US
1,1004,2002-05-31,361105,423860.0,5080,1.076539,6.537678,0.012231,0.150229,0.304851,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,000361105,US
2,1004,2002-08-31,361105,423860.0,5080,0.849232,6.565545,0.017054,0.144454,0.366410,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,000361105,US
3,1004,2003-08-31,361105,423860.0,5080,0.947754,6.531782,0.014462,0.242872,0.374171,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,000361105,US
4,1004,2003-11-30,361105,423860.0,5080,1.060599,6.516703,0.002641,0.239925,0.374254,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,000361105,US
5,1004,2004-02-29,361105,423860.0,5080,1.166620,6.501557,0.006578,0.254984,0.330967,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,000361105,US
6,1004,2004-05-31,361105,423860.0,5080,1.010184,6.580957,0.010363,0.232768,0.372406,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,000361105,US
7,1004,2004-08-31,361105,423860.0,5080,1.059771,6.564267,0.014502,0.234229,0.355366,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,000361105,US
8,1004,2004-11-30,361105,423860.0,5080,1.182439,6.550086,0.005154,0.244512,0.347932,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,000361105,US
9,1004,2005-02-28,361105,423860.0,5080,1.062619,6.566570,0.009424,0.236823,0.340630,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,000361105,US

### 2.2 LSTY(2024)

In [9]:
lsty = pd.read_excel("measures_2025.xlsx")
lsty.head(10)

,gvkey,year,qtr,phy_risk_acute_w,phy_risk_chronic_w,tran_risk_w,tran_risk_pro_w,tran_risk_npro_w
0,15704,2002,3,0.0,0.0,0.000000,0.0,0.000000
1,4990,2025,2,0.0,0.0,0.000000,0.0,0.000000
2,1686,2002,2,0.0,0.0,3.075031,0.0,3.075031
3,8488,2024,2,0.0,0.0,0.000000,0.0,0.000000
4,11234,2002,1,0.0,0.0,0.000000,0.0,0.000000
5,11234,2002,2,0.0,0.0,0.000000,0.0,0.000000
6,11234,2002,3,0.0,0.0,0.000000,0.0,0.000000
7,11234,2002,4,0.0,0.0,0.000000,0.0,0.000000
8,6532,2002,2,0.0,0.0,3.155570,0.0,3.155570
9,26011,2023,3,0.0,0.0,6.839945,0.0,6.839945

In [10]:
# repair "qtr"
lsty = lsty.rename(
    columns={
        "qtr": "quarter"
    }
)

In [18]:
dup_lsty = lsty[
    lsty.duplicated(
        subset=["gvkey","year","quarter"],
        keep=False
    )
].sort_values(
    ["gvkey","year","quarter"]
)

dup_lsty.head(20)

,gvkey,year,quarter,phy_risk_acute_w,phy_risk_chronic_w,tran_risk_w,tran_risk_pro_w,tran_risk_npro_w
39219,1004,2005,3,0.0,0.0,0.000000,0.0,0.000000
42534,1004,2005,3,0.0,0.0,0.000000,0.0,0.000000
56051,1004,2006,3,0.0,0.0,0.000000,0.0,0.000000
59320,1004,2006,3,0.0,0.0,0.000000,0.0,0.000000
74451,1004,2007,3,0.0,0.0,0.000000,0.0,0.000000
78163,1004,2007,3,0.0,0.0,0.000000,0.0,0.000000
94692,1004,2008,3,0.0,0.0,0.000000,0.0,0.000000
98660,1004,2008,3,0.0,0.0,0.000000,0.0,0.000000
115333,1004,2009,3,0.0,0.0,0.000000,0.0,0.000000
119466,1004,2009,3,0.0,0.0,0.000000,0.0,0.000000
127392,1004,2010,1,0.0,0.0,0.000000,0.0,0.000000
130430,1004,2010,1,0.0,0.0,0.000000,0.0,0.000000
131174,1004,2010,1,0.0,0.0,0.000000,0.0,0.000000
136867,1004,2010,3,0.0,0.0,0.000000,0.0,0.000000
140976,1004,2010,3,0.0,0.0,0.000000,0.0,0.000000
141884,1004,2010,4,0.0,0.0,0.000000,0.0,0.000000
146632,1004,2010,4,0.0,0.0,0.000000,0.0,0.000000
159177,1004,2011,3,0.0,0.0,0.000000,0.0,0.000000
163667,1004,2011,3,0.0,0.0,0.000000,0.0,0.000000
164830,1004,2011,4,0.0,0.0,1.246261,0.0,1.246261

In [20]:
dup_lsty.groupby(
    ["gvkey","year","quarter"]
)["tran_risk_w"].nunique().describe()

count    101750.000000
mean          1.530428
std           0.768405
min           1.000000
25%           1.000000
50%           1.000000
75%           2.000000
max          13.000000
Name: tran_risk_w, dtype: float64

In [23]:
# We should deal with REPLICATION!
# lsty
target_cols_lsty = lsty.select_dtypes(include=np.number).columns.tolist()

for c in ["gvkey", "year", "quarter"]:
    if c in target_cols_lsty:
        target_cols_lsty.remove(c)

# take means
lsty_avg = (
    lsty
    .groupby(["gvkey", "year", "quarter"], as_index=False)
    [target_cols_lsty]
    .mean()
)

print(len(lsty))
print(len(lsty_avg))

# examine again
print(
    lsty_avg.duplicated(
        subset=["gvkey","year","quarter"]
    ).sum()
)

598795
439996
0

In [26]:
# sautnerfin
# delete some vars
delete_var = ['cusip_x', 'isin', 'cusip_y', 'hqcountrycode']
sautnerfin = sautnerfin.drop(
    columns=delete_var,
    errors='ignore'
)

In [27]:
agg_dict = {}

for col in sautnerfin.columns:

    if col in ["gvkey", "year", "quarter"]:
        continue

    if pd.api.types.is_numeric_dtype(sautnerfin[col]):
        agg_dict[col] = "mean"
    else:
        agg_dict[col] = "first"

sautnerfin_avg = (
    sautnerfin
    .groupby(
        ["gvkey", "year", "quarter"],
        as_index=False
    )
    .agg(agg_dict)
)

print(
    sautnerfin_avg.duplicated(
        subset=["gvkey","year","quarter"]
    ).sum()
)

0

In [28]:
# link together
lstysautnerfin = sautnerfin_avg.merge(
    lsty_avg,
    on=["gvkey","year","quarter"],
    how="inner"
)

In [29]:
print(len(fin))
print(len(sautner))
print(len(sautnerfin))
print(len(lsty))
print(len(lstysautnerfin))

615927
259954
204208
598795
183228

In [30]:
lstysautnerfin.head(10)

,gvkey,year,quarter,datadate,naics,sic,tobinq,log_assets_lag,capex_lag,ppe_lag,...,ph_expo_ew,ph_risk_ew,ph_pos_ew,ph_neg_ew,ph_sent_ew,phy_risk_acute_w,phy_risk_chronic_w,tran_risk_w,tran_risk_pro_w,tran_risk_npro_w
0,1004,2002,1,2002-02-28,423860.0,5080.0,0.885511,6.571174,0.008598,0.147734,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1004,2002,2,2002-05-31,423860.0,5080.0,1.076539,6.537678,0.012231,0.150229,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1004,2002,3,2002-08-31,423860.0,5080.0,0.849232,6.565545,0.017054,0.144454,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1004,2003,3,2003-08-31,423860.0,5080.0,0.947754,6.531782,0.014462,0.242872,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1004,2003,4,2003-11-30,423860.0,5080.0,1.060599,6.516703,0.002641,0.239925,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,1004,2004,1,2004-02-29,423860.0,5080.0,1.166620,6.501557,0.006578,0.254984,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,1004,2004,2,2004-05-31,423860.0,5080.0,1.010184,6.580957,0.010363,0.232768,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,1004,2004,3,2004-08-31,423860.0,5080.0,1.059771,6.564267,0.014502,0.234229,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,1004,2004,4,2004-11-30,423860.0,5080.0,1.182439,6.550086,0.005154,0.244512,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,1004,2005,1,2005-02-28,423860.0,5080.0,1.062619,6.566570,0.009424,0.236823,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [31]:
# output
lstysautnerfin.to_excel(
    "lstysautnerfin.xlsx",
    index=False
)

In [32]:
sorted(lstysautnerfin["year"].unique())

[np.int32(2002),
 np.int32(2003),
 np.int32(2004),
 np.int32(2005),
 np.int32(2006),
 np.int32(2007),
 np.int32(2008),
 np.int32(2009),
 np.int32(2010),
 np.int32(2011),
 np.int32(2012),
 np.int32(2013),
 np.int32(2014),
 np.int32(2015),
 np.int32(2016),
 np.int32(2017),
 np.int32(2018),
 np.int32(2019),
 np.int32(2020),
 np.int32(2021),
 np.int32(2022),
 np.int32(2023),
 np.int32(2024)]